language: node_js
node_js:
- 10
branchs:
  only:
  - master
  - dev
notifications:
  email:
    recipients:
      - 18158501703@163.com
    on_success: always
    on_failure: always
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_51cb93dbcf43_key -iv $encrypted_51cb93dbcf43_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
install:
  - npm i
scripts:
  - npm run build
after_success:
  - scp -o StrictHostKeyChecking=no -r dist/* root@$ip:/usr/local/workspace/front-end/qingyu
addons:
  ssh_known_hosts: $ip